# Generated by Django 5.2.3 on 2025-06-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodItems',
            new_name='FoodItem',
        ),
    ]
