# Generated by Django 5.2.3 on 2025-06-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_rename_fooditems_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, max_length=5),
        ),
    ]
