# Generated by Django 5.2.3 on 2025-06-25 13:00

import FoodApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_alter_fooditem_price_alter_fooditem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='img_name',
            field=models.ImageField(storage=FoodApp.models.CustomStorage(), upload_to='items/'),
        ),
    ]
