# Generated by Django 5.2.3 on 2025-06-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_wallpaper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WallPaper',
        ),
    ]
