# Generated by Django 5.2.3 on 2025-06-25 16:40

import FoodApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0006_delete_wallpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.ImageField(storage=FoodApp.models.CustomStorage(), upload_to='wallpaper/')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
