# Generated by Django 5.2.3 on 2025-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_wallpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_type',
            field=models.CharField(choices=[('dessert', 'Dessert'), ('breakfast', 'Breakfast'), ('snacks', 'Snacks'), ('rice', 'Rice')], default='Breakfast', max_length=20),
        ),
    ]
