# Generated by Django 5.2.3 on 2025-07-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0008_fooditem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='cart',
            field=models.CharField(default=0),
        ),
    ]
