# Generated by Django 5.0.7 on 2024-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="email",
            field=models.EmailField(
                default="test@gmail.com", max_length=265, unique=True
            ),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="firstName",
            field=models.CharField(default="test", max_length=264),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="lastName",
            field=models.CharField(default="test", max_length=264),
        ),
    ]
